#pragma once

#ifndef ASYNC_UNITY_SHORT_NAMES
#define ASYNC_UNITY_SHORT_NAMES 1
#endif

#ifndef ASYNC_UNITY_SAFE_MEM_POOLS
#define ASYNC_UNITY_SAFE_MEM_POOLS 0
#endif

#ifndef ASYNC_UNITY_MAX_DEPTH
#define ASYNC_UNITY_MAX_DEPTH 10
#endif

#ifndef ASYNC_UNITY_LABEL_BUFFER_SIZE
#define ASYNC_UNITY_LABEL_BUFFER_SIZE 256
#endif

#ifndef ASYNC_UNITY_DEFAULT_TIMEOUT
#define ASYNC_UNITY_DEFAULT_TIMEOUT 2000
#endif

#ifndef ASYNC_UNITY_MAX_DESCRIBES
#define ASYNC_UNITY_MAX_DESCRIBES 100
#endif

#ifndef ASYNC_UNITY_MAX_ITS
#define ASYNC_UNITY_MAX_ITS 100
#endif

#ifndef ASYNC_UNITY_MAX_ASYNC_ITS
#define ASYNC_UNITY_MAX_ASYNC_ITS 100
#endif
