#pragma once

#ifndef BDD_UNITY_SHORT_NAMES
#define BDD_UNITY_SHORT_NAMES 1
#endif

#ifndef BDD_UNITY_SAFE_MEM_POOLS
#define BDD_UNITY_SAFE_MEM_POOLS 1
#endif

#ifndef BDD_UNITY_MAX_MODULE
#define BDD_UNITY_MAX_MODULE 5
#endif

#ifndef BDD_UNITY_MAX_DEPTH
#define BDD_UNITY_MAX_DEPTH 10
#endif

#ifndef BDD_UNITY_LABEL_BUFFER_SIZE
#define BDD_UNITY_LABEL_BUFFER_SIZE 256
#endif

#ifndef BDD_UNITY_DEFAULT_TIMEOUT
#define BDD_UNITY_DEFAULT_TIMEOUT 2000
#endif

#ifndef BDD_UNITY_MAX_DESCRIBE
#define BDD_UNITY_MAX_DESCRIBE 20
#endif

#ifndef BDD_UNITY_MAX_POP
#define BDD_UNITY_MAX_POP 20
#endif

#ifndef BDD_UNITY_MAX_TEST
#define BDD_UNITY_MAX_TEST 20
#endif

#ifndef BDD_UNITY_MAX_IT
#define BDD_UNITY_MAX_IT 20
#endif

#ifndef BDD_UNITY_MAX_ASYNC_IT
#define BDD_UNITY_MAX_ASYNC_IT 20
#endif

#ifndef BDD_UNITY_MAX_CALLBACK
#define BDD_UNITY_MAX_CALLBACK 20
#endif

#ifndef BDD_UNITY_MAX_ASYNC_CALLBACK
#define BDD_UNITY_MAX_ASYNC_CALLBACK 20
#endif

#ifndef BDD_UNITY_MAX_STACKED_CALLBACK
#define BDD_UNITY_MAX_STACKED_CALLBACK 20
#endif

#ifndef BDD_UNITY_MAX_STACKED_ASYNC_CALLBACK
#define BDD_UNITY_MAX_STACKED_ASYNC_CALLBACK 20
#endif

#ifndef BDD_UNITY_MAX_BEFORE_EACH
#define BDD_UNITY_MAX_BEFORE_EACH 20
#endif

#ifndef BDD_UNITY_MAX_ASYNC_BEFORE_EACH
#define BDD_UNITY_MAX_ASYNC_BEFORE_EACH 20
#endif

#ifndef BDD_UNITY_MAX_AFTER_EACH
#define BDD_UNITY_MAX_AFTER_EACH 20
#endif

#ifndef BDD_UNITY_MAX_ASYNC_AFTER_EACH
#define BDD_UNITY_MAX_ASYNC_AFTER_EACH 20
#endif

#ifndef BDD_UNITY_MAX_SETUP
#define BDD_UNITY_MAX_SETUP 20
#endif

#ifndef BDD_UNITY_MAX_LOOP
#define BDD_UNITY_MAX_LOOP 20
#endif
